
tasks:
  - name: terminal1
    init: echo 'init script' # runs during prebuild
    command: |
      echo 'start script'
      sudo apt-get install tldr #
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    # - ms-vscode.cpptools这是一个C/C++的依赖，因为线上平台没有提供，因此gitpod上无法从插件中找到，需要手动安装vsix，该插件包路径.\swb\ms-vscode.cpptools-1.7.1.vsix
    - formulahendry.code-runner
